version: '3.9'
services:
  client:
    image: akita-poker-client:latest
    environment: 
      SERVER_URL: server
      SERVER_PORT: "8080"
    depends_on:
      - server
  server:
    image: akita-poker-server:latest
    environment: 
      PORT: "8080"
    ports: 
      - 8080:8080