// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: hand.proto

package hand

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Face int64 `protobuf:"varint,1,opt,name=face,proto3" json:"face,omitempty"`
	Suit int64 `protobuf:"varint,2,opt,name=suit,proto3" json:"suit,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_hand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_hand_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetFace() int64 {
	if x != nil {
		return x.Face
	}
	return 0
}

func (x *Card) GetSuit() int64 {
	if x != nil {
		return x.Suit
	}
	return 0
}

type Hand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []*Card `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *Hand) Reset() {
	*x = Hand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hand_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hand) ProtoMessage() {}

func (x *Hand) ProtoReflect() protoreflect.Message {
	mi := &file_hand_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hand.ProtoReflect.Descriptor instead.
func (*Hand) Descriptor() ([]byte, []int) {
	return file_hand_proto_rawDescGZIP(), []int{1}
}

func (x *Hand) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type CheckHandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hand *Hand `protobuf:"bytes,1,opt,name=hand,proto3" json:"hand,omitempty"`
}

func (x *CheckHandRequest) Reset() {
	*x = CheckHandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hand_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckHandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHandRequest) ProtoMessage() {}

func (x *CheckHandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hand_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHandRequest.ProtoReflect.Descriptor instead.
func (*CheckHandRequest) Descriptor() ([]byte, []int) {
	return file_hand_proto_rawDescGZIP(), []int{2}
}

func (x *CheckHandRequest) GetHand() *Hand {
	if x != nil {
		return x.Hand
	}
	return nil
}

type CheckHandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hand *Hand  `protobuf:"bytes,2,opt,name=hand,proto3" json:"hand,omitempty"`
}

func (x *CheckHandResponse) Reset() {
	*x = CheckHandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hand_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckHandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHandResponse) ProtoMessage() {}

func (x *CheckHandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hand_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHandResponse.ProtoReflect.Descriptor instead.
func (*CheckHandResponse) Descriptor() ([]byte, []int) {
	return file_hand_proto_rawDescGZIP(), []int{3}
}

func (x *CheckHandResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckHandResponse) GetHand() *Hand {
	if x != nil {
		return x.Hand
	}
	return nil
}

var File_hand_proto protoreflect.FileDescriptor

var file_hand_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72,
	0x70, 0x63, 0x22, 0x2e, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x61, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x75, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x75,
	0x69, 0x74, 0x22, 0x28, 0x0a, 0x04, 0x48, 0x61, 0x6e, 0x64, 0x12, 0x20, 0x0a, 0x05, 0x63, 0x61,
	0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x32, 0x0a, 0x10,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x04, 0x68, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x52, 0x04, 0x68, 0x61, 0x6e, 0x64,
	0x22, 0x47, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x68, 0x61, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x48,
	0x61, 0x6e, 0x64, 0x52, 0x04, 0x68, 0x61, 0x6e, 0x64, 0x32, 0x4c, 0x0a, 0x0a, 0x48, 0x61, 0x6e,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x48, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x48, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hand_proto_rawDescOnce sync.Once
	file_hand_proto_rawDescData = file_hand_proto_rawDesc
)

func file_hand_proto_rawDescGZIP() []byte {
	file_hand_proto_rawDescOnce.Do(func() {
		file_hand_proto_rawDescData = protoimpl.X.CompressGZIP(file_hand_proto_rawDescData)
	})
	return file_hand_proto_rawDescData
}

var file_hand_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hand_proto_goTypes = []interface{}{
	(*Card)(nil),              // 0: grpc.Card
	(*Hand)(nil),              // 1: grpc.Hand
	(*CheckHandRequest)(nil),  // 2: grpc.CheckHandRequest
	(*CheckHandResponse)(nil), // 3: grpc.CheckHandResponse
}
var file_hand_proto_depIdxs = []int32{
	0, // 0: grpc.Hand.cards:type_name -> grpc.Card
	1, // 1: grpc.CheckHandRequest.hand:type_name -> grpc.Hand
	1, // 2: grpc.CheckHandResponse.hand:type_name -> grpc.Hand
	2, // 3: grpc.HandServer.CheckHand:input_type -> grpc.CheckHandRequest
	3, // 4: grpc.HandServer.CheckHand:output_type -> grpc.CheckHandResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hand_proto_init() }
func file_hand_proto_init() {
	if File_hand_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hand_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hand_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckHandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hand_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckHandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hand_proto_goTypes,
		DependencyIndexes: file_hand_proto_depIdxs,
		MessageInfos:      file_hand_proto_msgTypes,
	}.Build()
	File_hand_proto = out.File
	file_hand_proto_rawDesc = nil
	file_hand_proto_goTypes = nil
	file_hand_proto_depIdxs = nil
}
